//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36415
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalSummaryWeb.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoalDetails", Namespace="http://schemas.datacontract.org/2004/07/ClinicalSummaryService")]
    [System.SerializableAttribute()]
    public partial class GoalDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AchievedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CompletionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoalPriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> GoalStartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AchievedDate {
            get {
                return this.AchievedDateField;
            }
            set {
                if ((this.AchievedDateField.Equals(value) != true)) {
                    this.AchievedDateField = value;
                    this.RaisePropertyChanged("AchievedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CompletionDate {
            get {
                return this.CompletionDateField;
            }
            set {
                if ((this.CompletionDateField.Equals(value) != true)) {
                    this.CompletionDateField = value;
                    this.RaisePropertyChanged("CompletionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Goal {
            get {
                return this.GoalField;
            }
            set {
                if ((object.ReferenceEquals(this.GoalField, value) != true)) {
                    this.GoalField = value;
                    this.RaisePropertyChanged("Goal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoalPriority {
            get {
                return this.GoalPriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.GoalPriorityField, value) != true)) {
                    this.GoalPriorityField = value;
                    this.RaisePropertyChanged("GoalPriority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> GoalStartDate {
            get {
                return this.GoalStartDateField;
            }
            set {
                if ((this.GoalStartDateField.Equals(value) != true)) {
                    this.GoalStartDateField = value;
                    this.RaisePropertyChanged("GoalStartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IGoalService")]
    public interface IGoalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGoalService/GetDetails", ReplyAction="http://tempuri.org/IGoalService/GetDetailsResponse")]
        ClinicalSummaryWeb.ServiceReference.GoalDetails[] GetDetails(int memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGoalService/GetDetails", ReplyAction="http://tempuri.org/IGoalService/GetDetailsResponse")]
        System.Threading.Tasks.Task<ClinicalSummaryWeb.ServiceReference.GoalDetails[]> GetDetailsAsync(int memberId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGoalServiceChannel : ClinicalSummaryWeb.ServiceReference.IGoalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GoalServiceClient : System.ServiceModel.ClientBase<ClinicalSummaryWeb.ServiceReference.IGoalService>, ClinicalSummaryWeb.ServiceReference.IGoalService {
        
        public GoalServiceClient() {
        }
        
        public GoalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GoalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClinicalSummaryWeb.ServiceReference.GoalDetails[] GetDetails(int memberId) {
            return base.Channel.GetDetails(memberId);
        }
        
        public System.Threading.Tasks.Task<ClinicalSummaryWeb.ServiceReference.GoalDetails[]> GetDetailsAsync(int memberId) {
            return base.Channel.GetDetailsAsync(memberId);
        }
    }
}
